# Generated by Django 4.1.1 on 2022-09-20 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TerminalFuturesapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenelink',
            name='action',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scenelink',
            name='challengeAnswer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scenelink',
            name='challengeText',
            field=models.CharField(max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='scenelink',
            name='failScene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FailScene', to='TerminalFuturesapi.scene'),
        ),
        migrations.AlterField(
            model_name='scenelink',
            name='nextScene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NextScene', to='TerminalFuturesapi.scene'),
        ),
        migrations.AlterField(
            model_name='scenelink',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_links', to='TerminalFuturesapi.scene'),
        ),
    ]
